[features]
seeds = false
skip-lint = false

[programs.devnet]
hotkeys = "3pe5Hxtm7vtyoNXgfDei3DFheisFiZg8Xs8XkVbk4Hsz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
